### PR TITLE
composer update symfony/event-dispatcher range for laravel 6.0

### PR DESCRIPTION
**Pull request by se2129d**
hello :D

Nice to meet you.
I use your library in my old project. It's amazing library for gearman queue.
Now I create a new project need to require your library for gearman again.
But my new project is Laravel 6.0 base.
Laravel 6.0 need require `symfony/event-dispatcher: ^4.3`, so I run composer require is conflict.
I test your library on `symfony/event-dispatcher 4.4.7` independently, and It's working.
So I update `symfony/event-dispatcher` version range in composer.json.

### CODE REVIEW

**Comment by se2129d** [comment]
Thank you merge my PR.

Can you help me add new version tag for this PR ? Thank you. 😀

**Comment by dominikmank** [comment]
https://github.com/dominikmank/gearman/releases/tag/3.3.0 :)

**Comment by se2129d** [comment]
Sorry to bother you.
Can I ask why packagist no version 3.3.0?

https://packagist.org/packages/dmank/gearman

**Comment by dominikmank** [comment]
Now it's there. Sorry this lib is long forgotten for me and the only public libs in composer from myself..(the account link was broken :D) now it's up2date und auto syncing again.

**Pull request merged**
